server:
  port: 8090
  servlet:
    context-path: /api

yin:
  api:
    access-key: qqq1
    secret-key: qqq2

spring:
  application:
    name: yin-interface
dubbo:
  application:
    #服务应用名
    name: yin-interface-consuner-server
  #注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181